---
- hosts: tag_Type_demo
  gather_facts: false
  user: ubuntu
  tasks:
    - set_fact: ansible_ssh_private_key_file="~/.ssh/{{ hostvars[item].ec2_region }}.pem"
      with_items: "{{ inventory_hostname }}"
    # - name: Clean known_hosts
    #   local_action: shell ssh-keygen -f "~/.ssh/known_hosts" -R {{ inventory_hostname }}
    - name: Update known_hosts
      local_action: shell ssh-keyscan -t rsa {{ inventory_hostname }} >> $HOME/.ssh/known_hosts 2>&1
    - name: add current local user ssh key
      authorized_key: user=ubuntu key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
